export const environment = {
	production: true,
	TOKEN_TMDB: '',
	API_TMDB: 'https://api.themoviedb.org/3',
	API_BACKEND: '',
	API_BACKEND_RECOMMENDATION: '/api/recommendation',
	API_BACKEND_LAYOUT: "/api/layout",
	API_BACKEND_MOVIE: '/api/movie',
	API_BACKEND_SERIE: '/api/serie',
	API_BACKEND_USER: '/api/user',
	API_BACKEND_PROFILE: '/api/profile',
	API_BACKEND_SCORE: '/api/score',
	API_BACKEND_SEARCH: '/api/search',
	API_TMDB_IMAGE_ORIGINAL: 'https://image.tmdb.org/t/p/original',
	API_TMDB_IMAGE_REDUX: 'https://image.tmdb.org/t/p/w500',
	API_IMAGES_PROFILE: 'https://rickandmortyapi.com/api',
};
