export const environment = {
	production: false,
	TOKEN_TMDB: '',
	API_TMDB: 'https://api.themoviedb.org/3',
	API_BACKEND: 'http://localhost:3000',
	API_BACKEND_RECOMMENDATION: 'http://localhost:3000/api/recommendation',
	API_BACKEND_LAYOUT: "http://localhost:3000/api/layout",
	API_BACKEND_MOVIE: 'http://localhost:3000/api/movie',
	API_BACKEND_SERIE: 'http://localhost:3000/api/serie',
	API_BACKEND_USER: 'http://localhost:3000/api/user',
	API_BACKEND_PROFILE: 'http://localhost:3000/api/profile',
	API_BACKEND_SCORE: 'http://localhost:3000/api/score',
	API_BACKEND_SEARCH: 'http://localhost:3000/api/search',
	API_TMDB_IMAGE_ORIGINAL: 'https://image.tmdb.org/t/p/original',
	API_TMDB_IMAGE_REDUX: 'https://image.tmdb.org/t/p/w500',
	API_IMAGES_PROFILE: 'https://rickandmortyapi.com/api',
};
